name: kursol
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  intl_phone_field: ^3.2.0
  flutter_otp_text_field: ^1.1.1
  shared_preferences: ^2.2.1
  fluttertoast: ^8.2.12
#  flutter_share: ^2.0.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  flick_video_player: ^0.9.0
  get: ^4.6.6
  expansion_tile_card: ^3.0.0
  percent_indicator: ^4.2.3
  expandable_text: ^2.3.0
  flutter_screenutil: ^5.9.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  get_it: ^8.0.2
  dio: ^5.7.0
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gilroy-Regular.ttf
          weight: 400
    - family: AvenirLTPro
      fonts:
        - asset: assets/fonts/AvenirLTProMedium.otf
          weight: 700
